[theme]
primaryColor = "#1B7A34"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F5F5"
textColor = "#000000"
font = "sans serif"

[client]
toolbarMode = "minimal"
showErrorDetails = false

[logger]
level = "error"

[browser]
gatherUsageStats = false

[server]
port = 8501
headless = true
runOnSave = true
maxUploadSize = 200
enableXsrfProtection = true
